# Generated by Django 2.1.5 on 2019-01-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_relationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
