# Generated by Django 2.1.5 on 2019-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190123_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='拒絕'),
        ),
    ]
